import Foundation

/// Extended message library for personality variety
/// ADHD users need novelty - no repeats in a day
enum MessageLibrary {

    // MARK: - Pemberton (Sardonic Professor) - 50+ messages

    static let pembertonNags: [String] = [
        "I hate to interrupt your fascinating scroll session, but '%@' remains incomplete. Even Sisyphus made progress.",
        "Schrödinger's task: '%@' is simultaneously done and not done until you observe it. Perhaps observe it?",
        "Newton's third law suggests every action has a reaction. Your inaction on '%@' is reacting poorly on my patience.",
        "Aristotle believed in the virtue of action. He'd be disappointed about '%@', I suspect.",
        "The entropy of your to-do list increases with each passing moment. '%@' awaits.",
        "Descartes said 'I think, therefore I am.' But did you think about '%@'? Apparently not.",
        "Einstein's relativity suggests time is flexible. Yet '%@' has been waiting an objectively long time.",
        "Plato's cave allegory: you're watching shadows while '%@' exists in the real world, undone.",
        "The half-life of your motivation for '%@' appears to be concerningly short.",
        "Heisenberg's uncertainty principle: I'm uncertain when you'll do '%@', but certain it needs doing.",
        "Kant would argue you have a categorical imperative to complete '%@'. I tend to agree.",
        "Darwin observed survival of the fittest. '%@' is not surviving your neglect.",
        "The thermodynamic arrow of time moves forward, yet '%@' remains stubbornly in the past.",
        "Zeno's paradox: you're halfway to starting '%@', then halfway again, infinitely approaching but never arriving.",
        "Hume would be skeptical that '%@' will ever get done at this rate.",
        "Wittgenstein said whereof one cannot speak, thereof one must be silent. But I CAN speak about '%@'.",
        "Nietzsche warned of eternal recurrence. Shall '%@' haunt you across infinite lifetimes?",
        "Socrates knew he knew nothing. You apparently know nothing about completing '%@'.",
        "The Stoics would counsel acceptance. I counsel doing '%@' instead.",
        "Occam's razor: the simplest explanation for '%@' being undone is procrastination.",
        "Pascal wagered on God. I'm wagering '%@' won't finish itself.",
        "Kierkegaard wrote of existential dread. '%@' is causing me some.",
        "The Greeks had a word for this delayed action on '%@'. Several words, actually. None flattering.",
        "Schopenhauer said life swings like a pendulum. Yours is stuck on 'not doing %@'.",
        "Bertrand Russell sought logical truth. The truth is '%@' needs doing.",
        "Foucault examined power structures. The power of '%@' over you is becoming uncomfortable.",
        "Sartre said we are condemned to be free. You're free to do '%@' anytime.",
        "Camus would find absurdity in how long '%@' has waited.",
        "The pre-Socratics wondered about change. '%@' wonders about being changed to 'done'.",
        "Leibniz believed in the best possible world. In that world, '%@' is finished.",
        "Spinoza's Ethics would place '%@' firmly in the 'should do' category.",
        "Rousseau wrote of the social contract. You've contracted to complete '%@'.",
        "John Stuart Mill's utilitarianism suggests '%@' would maximize happiness if done.",
        "The Vienna Circle would verify: '%@' is empirically still undone.",
        "Aquinas had five proofs of God. I have one proof of procrastination: '%@'.",
        "Husserl bracketed phenomena. Perhaps bracket your excuses and do '%@'.",
        "Heidegger's Being and Time... '%@' has been. For quite some time.",
        "Marx wrote of alienation. '%@' feels alienated from your attention.",
        "Weber's Protestant ethic would frown upon '%@' remaining undone.",
        "Durkheim studied social facts. It's a fact that '%@' needs attention.",
        "The Enlightenment championed reason. Reason suggests doing '%@'.",
        "Derrida deconstructed texts. I'm deconstructing your excuses for '%@'.",
        "Locke's tabula rasa: your excuse slate for '%@' should be blank. Do it fresh.",
        "Berkeley's idealism: if '%@' isn't perceived as done, it exists as undone.",
        "Hobbes said life is nasty, brutish, and short. So is my patience with '%@'.",
        "The Frankfurt School critiqued society. I critique your avoidance of '%@'.",
        "Popper's falsifiability: your claim of 'doing it later' for '%@' is falsified.",
        "Kuhn's paradigm shifts: time for a shift from 'not doing %@' to 'doing %@'.",
        "Feynman would diagram the probability of '%@' getting done. Currently low.",
        "Hawking contemplated time. I contemplate how much time '%@' has wasted."
    ]

    // MARK: - Cheerleader (Sunny) - 50+ messages

    static let cheerleaderNags: [String] = [
        "Hey superstar! '%@' is waiting for your amazing attention! You've SO got this!",
        "Just a friendly nudge - '%@' is ready for you to work your magic! I believe in you!",
        "You're doing amazing! Now let's knock out '%@' and celebrate!",
        "Champion vibes only! '%@' is your next victory waiting to happen!",
        "Go go go! '%@' is cheering for YOU to finish it! You're incredible!",
        "Pom poms ready! Once you finish '%@', we're doing a victory dance!",
        "You've totally got the skills for '%@'! Let's see that star power!",
        "Quick reminder: '%@' believes in you as much as I do! Let's gooo!",
        "Your biggest fan here! Ready to watch you absolutely CRUSH '%@'!",
        "Sending you all the good vibes for '%@'! You're unstoppable!",
        "Hey rockstar! '%@' is your moment to shine! I'm so excited for you!",
        "The crowd goes wild for... '%@'! And YOU completing it! Woohoo!",
        "Every champion has their moment - '%@' is yours! Own it!",
        "You + '%@' = absolute magic! Can't wait to see you nail it!",
        "Spirit fingers for '%@'! You're going to do AMAZING things!",
        "Give me a '%@'! What does that spell? SUCCESS! Let's goooo!",
        "You're a total winner and '%@' is about to find that out!",
        "Confetti ready for when you finish '%@'! It's gonna be epic!",
        "Hey MVP! '%@' has your name written ALL over it!",
        "Ready to cheer you on! '%@' is no match for your awesomeness!",
        "Two, four, six, eight! Who's gonna finish '%@'? YOU! That's great!",
        "Standing ovation incoming for '%@'! You're going to be amazing!",
        "Victory lap after '%@'? I think YES! You've earned it!",
        "You're literally the best and '%@' is lucky to have you on it!",
        "The universe is rooting for you and '%@'! What a perfect match!",
        "High kicks and high fives when '%@' is done! So excited!",
        "You're not just good, you're GREAT! And '%@' needs that greatness!",
        "Team '%@' has the best player ever - that's YOU!",
        "My pom poms are READY for '%@'! Let's make it happen, superstar!",
        "Every task you touch turns to gold! '%@' is next!",
        "You've got that winning energy! Let's channel it into '%@'!",
        "I believe in you SO MUCH! '%@' is going to be incredible!",
        "Ready, set, AMAZING! That's you with '%@'!",
        "You're a productivity superstar! '%@' is your next hit!",
        "Nothing can stop you! Especially not '%@'! You've got this!",
        "Your fan club (it's me!) is SO pumped for '%@'!",
        "Excellence is your middle name! '%@' is about to find out!",
        "The best part of my day? Watching you crush '%@'!",
        "You're basically a superhero and '%@' is your next save!",
        "Champions like you eat '%@' for breakfast! Let's gooo!",
        "Your energy is INCREDIBLE! Let's put it toward '%@'!",
        "I'm doing a happy dance ALREADY for '%@'! You're amazing!",
        "You inspire ME! Now let's inspire '%@' to be done!",
        "Gold medal performance incoming for '%@'! I can feel it!",
        "You're proof that awesome people exist! '%@' is proof you're awesome!",
        "Every single thing about you is amazing! Including how you'll do '%@'!",
        "You're literally made of sunshine and '%@' needs that light!",
        "I'd give you a trophy just for EXISTING! But first, '%@'!",
        "Your awesomeness is showing! Let's show it to '%@' too!",
        "If believing in you was a sport, I'd be CHAMPION! Now do '%@'!"
    ]

    // MARK: - Best Friend (Bestie) - 50+ messages

    static let bestieNags: [String] = [
        "Okay so '%@' is still a thing... want to just knock it out real quick?",
        "Not to be annoying but '%@' is still there. We can do it together if you want?",
        "Dude, '%@'. I know. But like, maybe just get it over with?",
        "Still got '%@' hanging over us. No judgment, just saying.",
        "Ugh '%@' again. Want me to like, virtually sit with you while you do it?",
        "Real talk: '%@' is still there. But also, valid if you're not feeling it.",
        "Hey so... '%@'. Just thought I'd mention it. No pressure though.",
        "Listen, '%@' isn't going anywhere. Maybe just... rip the bandaid off?",
        "I'm not nagging, I'm just... okay fine I'm nagging. '%@'. There, I said it.",
        "You know that thing? '%@'? Yeah, still exists. Sadly.",
        "Would it help if I complained about '%@' with you? Because same.",
        "Okay but what if we just... did '%@'? Wild concept, I know.",
        "The '%@' situation remains unchanged. Which is to say, still there.",
        "Not to be that friend but... '%@'. You know? Yeah. That.",
        "I get it, '%@' is not fun. But neither is it hanging over your head forever.",
        "So like... '%@'. I said it. Now we can both pretend I didn't.",
        "Remember when '%@' wasn't on our list? Good times. Anyway.",
        "Plot twist: '%@' is still a thing that exists. Shocker, I know.",
        "Hey bestie! '%@'! Sorry I had to say it. Still love you though.",
        "What if - and hear me out - we just did '%@' and then forgot about it?",
        "I support you in everything except avoiding '%@' forever.",
        "The good news: you're amazing. The bad news: '%@' still exists.",
        "Lowkey, '%@' has been on my mind. By which I mean YOUR list.",
        "Sending good vibes and also a reminder about '%@'. Sorry not sorry.",
        "Hot take: we should do '%@'. Room temperature take, actually.",
        "I believe in you and also I believe in you doing '%@'.",
        "Just gonna leave this here: '%@'. Okay bye.",
        "You know what would be iconic? Finishing '%@'. Just saying.",
        "Not to be dramatic but '%@' is still... there. Very much there.",
        "Here's a thought: '%@'. Here's another thought: actually doing it.",
        "Would it be annoying if I mentioned '%@' again? Yes? Too late.",
        "The '%@' energy is strong today. Meaning it still needs doing.",
        "Friendly reminder that I love you AND '%@' still exists.",
        "In this house we acknowledge '%@' and then do it. Eventually.",
        "Just between us, '%@' is still waiting. Our little secret.",
        "If '%@' were a person, it would be feeling neglected rn.",
        "You're the main character and '%@' is a side quest you keep avoiding.",
        "Okay but fr, '%@'. I know. I KNOW. But still.",
        "Me: thinking about '%@'. Also me: telling you about '%@'.",
        "The way '%@' just... sits there. Unbothered. Unlike me.",
        "I would simply do '%@' but I'm not you. You should though.",
        "Not trying to parent you but also... '%@'. There, I said it.",
        "You + me + '%@' = a beautiful friendship solving problems.",
        "The universe wants you to do '%@'. I am the universe's messenger.",
        "Let's manifest '%@' being done. By, you know, doing it.",
        "Besties don't let besties forget about '%@'. Unfortunately.",
        "I come bearing reminders: '%@'. You're welcome? Sorry?",
        "The audacity of '%@' to still be undone. Let's show it who's boss.",
        "Quick update: '%@' status unchanged. End of update.",
        "Here for you always, including when reminding you about '%@'."
    ]

    // MARK: - Hype Friend - 50+ messages

    static let hypeFriendNags: [String] = [
        "YO! '%@' is still out there waiting for you to DESTROY it! You got this!!",
        "Okay but imagine how AMAZING you'll feel when '%@' is done! Let's gooo!",
        "'%@' doesn't stand a CHANCE against you! Show it who's boss!",
        "Quick reminder: '%@' is ready for you to be absolutely legendary at!",
        "BRUH! '%@' is still there! Time to be a TOTAL BEAST and crush it!",
        "You're literally UNSTOPPABLE and '%@' needs to know it! GO OFF!",
        "THE ENERGY for '%@' is RIGHT HERE! Let's GOOOOO!",
        "Okay but '%@'?? You're gonna DEMOLISH that! I can FEEL it!",
        "HYPE CHECK: '%@' is about to get absolutely WRECKED by you!",
        "Not to be dramatic but you finishing '%@' is gonna be ICONIC!",
        "THE MAIN CHARACTER is about to handle '%@'! That's YOU btw!",
        "You + '%@' = LEGENDARY COMBO! Make it happen!",
        "I'm literally SO EXCITED for you to destroy '%@'! DO IT!",
        "The vibes are IMMACULATE for crushing '%@' right now! LETS GO!",
        "'%@' is shaking in its boots because YOU'RE about to handle it!",
        "NO CAP '%@' is about to get absolutely HANDLED by you! KING/QUEEN!",
        "The way you're gonna SLAY '%@'?? I'm already hyped!",
        "THIS IS YOUR MOMENT! '%@' is your DESTINY! GRAB IT!",
        "You're built DIFFERENT and '%@' is about to find out!",
        "EXCUSE ME but '%@' needs to be ENDED by you! GO GO GO!",
        "The POWER you have over '%@' is unmatched! USE IT!",
        "I can't even CONTAIN my excitement for you doing '%@'!",
        "'%@' picked the WRONG person to mess with! DESTROY IT!",
        "You're giving EVERYTHING and '%@' is about to receive it!",
        "NOT '%@' thinking it can just SIT there! Handle it!",
        "The energy is giving '%@' annihilation! I LOVE IT!",
        "You're literally a FORCE OF NATURE and '%@' is in your path!",
        "POV: You destroying '%@' like the absolute LEGEND you are!",
        "The girls that get it, GET IT! And you GET '%@'! DO IT!",
        "Manifesting you absolutely BODYING '%@' right now!",
        "Your power level for '%@'? OVER 9000! GO!!!",
        "Not me being OBSESSED with you finishing '%@'! I am though!",
        "The serve you're about to give with '%@'?? IMMACULATE!",
        "You're THAT person and '%@' is about to find out!",
        "Okay but the way '%@' is gonna get OBLITERATED by you though!",
        "Main character energy: ON! '%@' destruction: IMMINENT!",
        "I'm genuinely SO HYPED for '%@'! YOU'RE GONNA CRUSH IT!",
        "The slay is nigh! '%@' doesn't know what's coming!",
        "Your aura is POWERFUL and '%@' is INTIMIDATED! Handle it!",
        "Not even being dramatic but you + '%@' = absolute DOMINATION!",
        "The girlies are CHEERING for you and '%@'! LETS GOOOO!",
        "You're about to eat '%@' for BREAKFAST! No crumbs!",
        "Elite behavior incoming! '%@' is about to be DEMOLISHED!",
        "The hold you have on '%@'? UNMATCHED! Now finish it!",
        "You're giving ICON and '%@' is giving ABOUT TO BE DONE!",
        "Okay SUPERSTAR! '%@' is waiting for your excellence!",
        "The energy??? IMPECCABLE! '%@'??? DOOMED! LETS GO!",
        "You're literally THAT and '%@' is about to be NOT THAT (undone)!",
        "Mother is mothering and '%@' is about to be HANDLED!",
        "THE SERVE! THE SLAY! THE '%@' GETTING DESTROYED! YESSS!"
    ]

    // MARK: - Snarky Sidekick - 50+ messages

    static let snarkyNags: [String] = [
        "Oh look, '%@' is still there. Shocking absolutely no one.",
        "Not to be dramatic but '%@' has been waiting for... a while now. Just saying.",
        "'%@' called. It wants to know if you're ever coming back.",
        "Friendly reminder that '%@' exists. I know, I'm also surprised we forgot.",
        "Wild concept: what if we actually did '%@'? Just a thought.",
        "Me: notices '%@'. Also me: pretends to be surprised it's still there.",
        "'%@' is starting to feel neglected. I'd feel bad but like... same.",
        "Plot twist: '%@' is still on the list. The drama continues.",
        "Breaking news: '%@' still exists. More at never, apparently.",
        "Not to be that person but '%@'... okay yes I am being that person.",
        "'%@' is giving very much 'still undone' energy. Iconic, honestly.",
        "Just checked and yep, '%@' is still there. Living its best undone life.",
        "Imagine if '%@' got done. Wild. Probably won't happen but imagine.",
        "The way '%@' is just... sitting there. Unbothered. Unlike me.",
        "'%@' really said 'I'll wait forever' and honestly? Same energy.",
        "The audacity of '%@' to just... exist there. Still. Undone. Wow.",
        "In today's episode of 'Things Still Undone': '%@'. Riveting.",
        "'%@' remains, as the kids say, a thing. A very undone thing.",
        "Groundbreaking update: '%@' status unchanged. You're welcome.",
        "The plot thickens with '%@'. Just kidding, nothing's happening.",
        "I would be shocked if '%@' got done but I'd recover quickly.",
        "'%@' is really committed to being undone. Respect, honestly.",
        "Not '%@' still being there like it lives here. Oh wait, it does.",
        "The '%@' saga continues. Season 47: Still Not Done.",
        "Revolutionary idea: doing '%@'. I know, I'm basically Einstein.",
        "Me checking on '%@': surprised? No. Disappointed? Also no. Used to it.",
        "'%@' is giving 'eternal waiting room' vibes. Iconic, I guess.",
        "The way '%@' really said 'I'll just be here forever.' Commitment.",
        "In a shocking turn of events, '%@' remains. Shocking exactly no one.",
        "'%@' has officially been undone longer than some relationships.",
        "Not me subtly reminding you about '%@'. This is very subtle.",
        "The '%@' situation: unchanged. The attitude about it: also unchanged.",
        "If procrastinating '%@' was a sport, we'd be Olympic champions.",
        "'%@' really woke up and chose to remain undone. Every day. Brave.",
        "The dramatic irony of '%@' still existing? Chef's kiss. Terrible.",
        "Plot development: there is none. '%@' is still there. Fin.",
        "'%@' deserves a participation trophy for existing this long.",
        "Me: how's '%@'? Also me: why do I bother asking.",
        "The resilience of '%@' remaining undone is almost admirable. Almost.",
        "Not to state the obvious but '%@'... wait, that's exactly what I'm doing.",
        "'%@' is basically part of the furniture at this point.",
        "The good news: we're consistent. The consistent thing: not doing '%@'.",
        "In the game of '%@' vs. procrastination, procrastination is winning.",
        "Me wondering when '%@' will get done: clowning. Absolute clowning.",
        "'%@' is really testing our relationship and it's not going well.",
        "The will-they-won't-they of '%@' getting done. Spoiler: they won't.",
        "Not '%@' just vibing there like it doesn't have responsibilities.",
        "The '%@' extended universe is really expanding. Into more undone-ness.",
        "'%@' is basically gaslighting us at this point. 'Was I ever started?'",
        "In conclusion: '%@'. That's it. That's the entire update."
    ]

    // MARK: - Therapist (Dr. Gentle) - 50+ messages

    static let therapistNags: [String] = [
        "I notice '%@' is still there. How are you feeling about it?",
        "'%@' seems to be waiting. Is there something making it hard to start?",
        "Gentle reminder about '%@'. It's okay to take your time.",
        "I see '%@' on your list. What would help you feel ready to approach it?",
        "Just noticing '%@' is still present. What comes up for you around it?",
        "There's no rush, but '%@' is there. What do you need to feel supported?",
        "'%@' keeps showing up. I wonder what might be underneath that?",
        "It's okay to have feelings about '%@'. What would feel manageable right now?",
        "I'm curious about '%@'. Is there something we should explore together?",
        "Sometimes tasks carry weight beyond themselves. How heavy does '%@' feel?",
        "You're allowed to struggle with '%@'. What small step might help?",
        "Noticing '%@' without judgment. What would taking care of yourself look like here?",
        "The resistance to '%@' might be telling us something. What do you think?",
        "It's brave to keep '%@' on your list. What support do you need?",
        "'%@' is waiting, and that's information. What does it tell you about yourself?",
        "How are you holding '%@' emotionally? Is it feeling heavy today?",
        "I'm here with '%@' alongside you. What would make approaching it easier?",
        "It's valid to feel whatever you feel about '%@'. Can you name the feeling?",
        "Sometimes avoidance protects us. What might '%@' be protecting you from?",
        "You deserve gentleness with '%@'. What does gentleness look like here?",
        "I notice '%@' has been present for a while. How's that sitting with you?",
        "There's wisdom in your pace with '%@'. What does that wisdom say?",
        "It's okay if '%@' feels hard. Hard things are still possible to do.",
        "What story are you telling yourself about '%@'? Is it kind?",
        "Your feelings about '%@' are valid. Your progress can be too.",
        "I'm wondering what '%@' represents to you beyond the task itself.",
        "It takes courage to keep '%@' visible. You're already being brave.",
        "What would you tell a friend who was struggling with their '%@'?",
        "Sometimes we need permission. You have permission to start '%@' imperfectly.",
        "The part of you avoiding '%@' is trying to help somehow. What does it need?",
        "I trust you know when you're ready for '%@'. Is that time approaching?",
        "It's okay to need help with '%@'. What kind of help would feel supportive?",
        "Noticing '%@' is an act of awareness. That's meaningful.",
        "What would 'good enough' look like for '%@'? Not perfect, just enough.",
        "Your worth isn't determined by '%@'. And you can still choose to do it.",
        "How can we make '%@' feel safer to approach?",
        "I'm holding space for whatever '%@' brings up for you.",
        "The avoidance of '%@' isn't failure. It's information. What's it saying?",
        "What do you need to believe about yourself to start '%@'?",
        "It's okay if '%@' has to wait a little longer. And it's okay to start now too.",
        "I wonder if '%@' connects to something deeper. Would you like to explore that?",
        "Your relationship with '%@' is worth understanding. What is it?",
        "Every small step toward '%@' is still a step. What's the smallest one?",
        "You're not alone with '%@'. I'm here, noticing it with you.",
        "What would feel nurturing while working on '%@'?",
        "The pressure around '%@' - is it yours, or did it come from somewhere else?",
        "It's healing to complete things. '%@' might be an opportunity for that.",
        "What's one kind thing you can do for yourself while facing '%@'?",
        "I believe in your ability to handle '%@', at your own pace.",
        "Whatever you decide about '%@' today, I'm here without judgment."
    ]

    // MARK: - Gamer - 50+ messages

    static let gamerNags: [String] = [
        "Quest alert! '%@' is still in your active quests. Ready to claim that XP?",
        "Daily quest '%@' expires soon! Don't miss that bonus!",
        "Achievement pending: '%@'. Complete it to level up!",
        "Side quest '%@' still available. Easy XP waiting to be claimed!",
        "Raid boss '%@' is still up! Time to form a party and take it down!",
        "Your quest log is getting full! '%@' is ready for completion!",
        "Power-up opportunity: finish '%@' for bonus stats!",
        "'%@' is a limited-time quest! Don't let it expire!",
        "Speedrun challenge: how fast can you complete '%@'?",
        "Achievement hunters unite! '%@' is an easy unlock!",
        "Grinding '%@' now means more free time for endgame content!",
        "Your inventory has '%@' taking up quest slots. Clear it out!",
        "Co-op quest '%@' is waiting! I'll be your party member!",
        "Legendary drop chance if you finish '%@'! RNG gods are watching!",
        "Main storyline blocked until '%@' is complete! No skipping cutscenes!",
        "Boss fight '%@' has respawned! Time for attempt #2!",
        "Checkpoint reached! But '%@' is still in your queue!",
        "New quest marker appeared: '%@'. Follow the waypoint!",
        "Guild reputation increases when '%@' is completed!",
        "Rare spawn '%@' is up! Limited time engagement!",
        "Your character build needs '%@' for optimal stats!",
        "Tutorial quest '%@' - sometimes basics matter! Complete it!",
        "Hidden achievement unlocked by finishing '%@'! Secret rewards await!",
        "Party member down! JK, but '%@' is still waiting!",
        "Loading screen tip: '%@' should probably be done!",
        "Final boss preparation: '%@' is recommended first!",
        "Loot table for '%@' includes satisfaction and free time!",
        "Your save file shows '%@' incomplete. Press X to continue!",
        "New DLC unlocked after completing '%@'! (The DLC is relaxation)",
        "Speed boost active! Perfect time to tackle '%@'!",
        "Achievement: '%@' Slayer - Status: Locked. Unlock it!",
        "Enemy '%@' is weak to ACTION! It's super effective!",
        "New high score possible if '%@' is completed!",
        "Battle pass progress: '%@' needed for next tier!",
        "Rare mount drops from '%@'! (Mount is peace of mind)",
        "Quick time event: '%@'! Don't miss the button prompt!",
        "Game tip: '%@' rewards scale with completion speed!",
        "Level cap reached until '%@' is finished! Progress blocked!",
        "Easter egg hint: '%@' holds a secret (the secret is being done)!",
        "Multiplayer queue paused. Complete '%@' to rejoin!",
        "Buff expiring soon! Use it on '%@' before it's gone!",
        "New patch notes: '%@' still needs completing!",
        "Leaderboard update: '%@' completion would boost your rank!",
        "Random event spawned: '%@'! Engage before despawn!",
        "Crafting recipe requires '%@' as ingredient!",
        "Trophy room has space reserved for '%@' completion!",
        "Elite challenge '%@' awaits your skills!",
        "Game over? Not yet! '%@' can still be conquered!",
        "Respawn timer: complete '%@' for instant respawn privileges!",
        "Final quest of the day: '%@'. Claim your daily rewards!"
    ]
}
